server:
  port: 7080
swagger:
  basePackage: com.shark.example
spring:
  application:
    name: Example
  messages:
    basename: i18n/messages
    encoding: UTF-8
logging:
  level:
    com:
      shark:
        example: INFO