server:
  port: 8082
spring:
  messages:
    basename: i18n/message
    encoding: UTF-8
  cassandra:
    schema-action: CREATE_IF_NOT_EXISTS
    keyspace-name: example
    contact-points: 127.0.0.1
    local-datacenter: datacenter1
    port: 9042
    request:
      timeout: 5s

