server:
  port: 8080
spring:
  messages:
    basename: i18n/message
    encoding: UTF-8
  data:
    redis:
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
      host: 127.0.0.1
      port: 6379
      password: ""