version: '3.8'
services:
  emqx:
    image: emqx/emqx:5.8.1
    container_name: emqx
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=127.0.0.1
    ports:
      - "1883:1883" # MQTT 端口
      - "8083:8083" # WebSocket 端口
      - "18083:18083" # 管理儀表板
    volumes:
      - emqx-data:/opt/emqx/data
    networks:
      - emqx-example

volumes:
  emqx-data:

networks:
  emqx-example:
    driver: bridge