version: '3'

services:
  scylla-node1:
    image: scylladb/scylla:latest
    container_name: scylla-node1
    ports:
      - "9042:9042"
      - "9180:9180"
    environment:
      - SCYLLA_EXTRA_ARGS=--batch-size-fail-threshold-in-kb 4096
    command: --seeds=scylla-node1 --smp 1
    networks:
      - scylla-net
networks:
  scylla-net:
    driver: bridge