version: '1'
services:
  rabbitmq_example:
    image: rabbitmq:management
    container_name: example_rabbit_mq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"