version: '3'

services:
  scylla-node1:
    image: scylladb/scylla:latest
    container_name: scylla-node1
    ports:
      - "9042:9042"
    command: --seeds=scylla-node1 --smp 1 --overprovisioned 1 --api-address 0.0.0.0
    networks:
      - scylla-net
  scylla-node2:
    image: scylladb/scylla:latest
    container_name: scylla-node2
    command: --seeds=scylla-node1 --smp 1 --overprovisioned 1 --api-address 0.0.0.0
    networks:
      - scylla-net
  scylla-node3:
    image: scylladb/scylla:latest
    container_name: scylla-node3
    command: --seeds=scylla-node1 --smp 1 --overprovisioned 1 --api-address 0.0.0.0
    networks:
      - scylla-net
networks:
  scylla-net:
    driver: bridge