version: '1'
services:
  mysql_example:
    image: mysql:8
    container_name: example_mysql
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: example
      TZ: Asia/Hong_Kong
    ports:
      - "3306:3306"